- name: clone AstroNvim
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/AstroNvim
    dest: "{{ ansible_env.HOME }}/.config/nvim"

- name: AstroNvim - run MasonInstall
  ansible.builtin.shell: nvim  --headless -c 'MasonInstall black isort yamlfmt markdownlint jsonlint shellcheck pyright yaml-language-server marksman json-lsp gopls dockerfile-language-server bash-language-server awk-language-server ansible-language-server'
  async: 10
  poll: 0

- name: AstroNvim - run PackerSync
  ansible.builtin.shell: nvim  --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  async: 10
  poll: 0